CREATE OR REPLACE PACKAGE autentykacja
IS
	TYPE tablica_agenta IS TABLE OF VARCHAR2(100 CHAR) INDEX BY VARCHAR2(100 CHAR);

	FUNCTION sys_op(wartosc VARCHAR2) RETURN VARCHAR2;

	FUNCTION przegl(wartosc VARCHAR2) RETURN VARCHAR2;

	FUNCTION jezyk(wartosc VARCHAR2) RETURN VARCHAR2;
END autentykacja;